import torch
print(torch.cuda.is_available())
print(torch.version.cuda)
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
print(torch.cuda.current_device())
tensor = torch.randn(3, 3)
tensor = tensor.to('cuda')
print(tensor)
print("Hello World")
